import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from '../components/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(
  
  {
  children,
}: {
  children: React.ReactNode
}

) {
  var iconHeight = 40
  var iconWidth = 40
  const links = [
    {label:"Main Menu",path:"/",icon:"./mainMenu.svg"},
    {label:"Play",path:"/game",icon:"./playIcon.svg"},
    {label:"Learn",path:"/learn",icon:"./learnIcon.svg"}
  ]
  return (
    <html lang="en">
      <head/>
      <body className={inter.className}>
        <div className='block'>
          <header className="bg-white">
            <nav className="-m-0 p-0 w-52 bg-neutral-800 fixed overflow-auto h-full" aria-label="Global">
              {links.map((link,i)=>{
                return <Link label={link.label} path={link.path} key={link.label + i} icon={link.icon}></Link>
              })}
            </nav>
          </header>
        </div>
        <main className='ml-52 pl-4'>
          {children}
        </main>
      </body>
    </html>
  )
}
